### ISSUE TITLE
Not an issue, but are there any examples of plugins that use this framework? 

### ISSUE THREAD

**Issue by CodeBradley** [betrueagency/nx-reactjs-elementor#15]
I'm looking for some code examples and/or any Elementor Widgets built with React.

**Comment by alizarion** [comment]
hi @CodeBradley 
The purpose of this plugin is to generate sample code to create these widgets.

I don't know if any opensource project uses this plugin, we mainly use it for our customers' projects that need to expose the business logic of their application on a website.
 
it is very discreet because it is completely integrated into the elementor website
here are some examples
https://nomadchoice.com/open-countries/ => map
https://www.betrue.fr/team/ => team synchronized with the staffing tool
https://www.betrue.fr/rejoignez-la-team-betrue/ => onboarding process synchronized with staffing tools
https://www.marcelsenchou.fr/des-endroits/ => map synchronized with partner management tool

**Comment by alizarion** [comment]
Another example of how it can be used 
https://www.pickfoot.com/ => store locator and settings widgets were created with this plugin
